Feature/538 update project muse onix export
thoth-pub/thoth pull request #609
Opened 2024-07-09 14:42 UTC by brendan-oconnell

https://github.com/thoth-pub/thoth/issues/538

2024-07-10 13:08 UTC, rhigman requested changes
Could also add the `EditionStatement` tag (between contributors and languages) - awkward that they apparently don't support `EditionNumber`, but there's logic for constructing the verbal statement [in the MARC export](https://github.com/thoth-pub/thoth/blob/a178ea883540bcb99a2d6b9af450f0ccfcb5fca0/thoth-export-server/src/marc21/marc21record_thoth.rs#L216).

Looks good overall, thanks!

2024-07-10 13:35 UTC, brendan-oconnell commented on thoth-export-server/src/xml/onix3_project_muse.rs
> +                        // According to spec, Project MUSE only accepts BIC and BISAC subject codes
Yes, I think you're right - no need to remove them in this case.

2024-07-10 13:36 UTC, brendan-oconnell commented on thoth-export-server/src/xml/onix3_project_muse.rs
> +                                "02".to_string(),
Yeah, I also noticed that many other outputs use 01, but I agree that 02 is generally going to be more appropriate - and in this case, follows Project MUSE's spec. I agree that it seems like a good idea to fix this in the other outputs.

2024-07-10 13:55 UTC, brendan-oconnell commented
> Could also add the `EditionStatement` tag (between contributors and languages) - awkward that they apparently don't support `EditionNumber`, but there's logic for constructing the verbal statement [in the MARC export](https://github.com/thoth-pub/thoth/blob/a178ea883540bcb99a2d6b9af450f0ccfcb5fca0/thoth-export-server/src/marc21/marc21record_thoth.rs#L216).
> 
> Looks good overall, thanks!

Thanks! I agree that it's weird that we can't just put in `EditionNumber`, but the MARC logic was helpful for `EditionStatement`, thanks for that!

2024-07-11 11:40 UTC, rhigman approved these changes

2024-07-11 11:57 UTC, merged

2024-07-11 13:05 UTC, ja573 commented on thoth-export-server/src/xml/onix3_project_muse.rs
> +                                "02".to_string(),
We based the majority of the ONIX outputs on OAPEN's, so now that they've confirmed they're happy with us changing the code to 02 let's update it in the rest and look out for any potential complains

2024-07-11 13:43 UTC, brendan-oconnell commented on thoth-export-server/src/xml/onix3_project_muse.rs
> +                                "02".to_string(),
Great, I'll create an issue for this.