Feature/634 659 prevent changing work status back prevent post publication deletion
thoth-pub/thoth pull request #663
Opened 2024-12-16 13:51 UTC by brendan-oconnell

2025-04-03 09:32 UTC, ja573 requested changes
Okay, so it looks like the modal component is not _just_ a modal, but it's the work form's save button _and_ the confirmation modal.

The work form has a callback on submit (UpdataWork). You need to modify that callback so that if the modal is not required the callback is UpdateWork, but if it _is_ required it should open the modal instead.

Then you can make use of the callback in the modal to update the work.

```mermaid
graph TD;
    subgraph Work Form
        A[User Submits Work Form] -->|Needs Confirmation?| B{Check Confirmation}
        B -- No --> C[Call UpdateWork Directly]
        B -- Yes --> D[Open Confirmation Modal]
    end

    subgraph Confirmation Modal
        D --> E[User Confirms]
        E --> F[Call UpdateWork from Modal]
    end
```

2025-04-03 09:32 UTC, ja573 commented on thoth-app/src/component/work_status_modal.rs
> +    pub onsubmit: Callback<()>,
this callback isn't actually used

2025-04-03 09:32 UTC, ja573 commented on thoth-app/src/component/work_status_modal.rs
> +            Msg::CloseModalAndUpdateWork => {
This variant isn't actually updating anything, so let's just call it `CloseModal`

2025-04-15 16:10 UTC, ja573 requested changes

2025-04-15 16:10 UTC, ja573 commented on thoth-app/src/component/work_status_modal.rs
> +    pub is_published: bool,
there seem to be a bunch of properties with no use

2025-04-15 16:10 UTC, ja573 commented on thoth-app/src/component/work.rs
> +                                    // div key generates random uuid and forces re-render of the ConfirmWorkStatusComponent
I'm not actually able to recreate this behaviour

2025-04-16 09:07 UTC, brendan-oconnell commented on thoth-app/src/component/work.rs
> +                let current_state_unpublished = self.current_work_status == WorkStatus::Forthcoming
I agree for that I can replace 

```
                let is_published = self.work.work_status == WorkStatus::Active
                    || self.work.work_status == WorkStatus::Withdrawn
                    || self.work.work_status == WorkStatus::Superseded;
```

with `let is_published = self.is_published();`

but for `current_state_unpublished`, I'm looking at `WorkStatus` directly. The `is_published()` function in `mod.rs` takes a `WorkComponent` as an argument, not a `WorkStatus`.

2025-04-16 09:27 UTC, ja573 commented on thoth-app/src/component/work.rs
> +                let current_state_unpublished = self.current_work_status == WorkStatus::Forthcoming
in that case you can just add `is_currently_published` as a component property

2025-04-18 09:26 UTC, brendan-oconnell commented on thoth-app/src/component/work.rs
> +                                    // div key generates random uuid and forces re-render of the ConfirmWorkStatusComponent
I just re-tested and I'm not getting the behavior any more either, so I deleted the div and key!

2025-04-22 09:36 UTC, ja573 requested changes

2025-04-22 09:36 UTC, ja573 commented on thoth-app/src/component/work.rs
the idea here is to replace all individual WorkStatus checks with the status API (is_published, etc.)

2025-04-24 07:53 UTC, ja573 approved these changes

2025-04-24 08:45 UTC, merged